version: '3'
services:
  # app:
  #   container_name: backend-pepsico
  #   restart: always
  #   build: .
  #   ports:
  #     - 3333:3333
  #     - 9229:9229 #debug port
  #   external_links:
  #     - mongo
  #     - postgres
  #     - redis
  #   volumes:
  #     - ./:/home/node/api
  #     - ./node_modules:/home/node/api/node_modules
  #   networks:
  #     - app-connect

  postgres:
    container_name: postgres-nodejs
    image: postgres:11
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres-data-backend:/data
    networks:
      - app-connect

volumes:
  postgres-data-backend:

networks:
  app-connect:
    driver: bridge
